openapi: 3.0.1
info:
  title: '@jupiterone/graph-cisco-meraki'
  description: A graph conversion tool for https://meraki.cisco.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cisco-meraki
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-cisco-meraki'
